import type { Metadata } from "next";
import localFont from "next/font/local";
import "remixicon/fonts/remixicon.css";
import "./globals.css";
import Footer from "@/components/layout/footer";
import Sidebar from "@/components/layout/sidebar";

const noto = localFont({
  src: "./fonts/NotoSansDisplay.ttf",
  variable: "--font-noto-sans-display",
  weight: "100 900",
});

const inter = localFont({
  src: "./fonts/inter.ttf",
  variable: "--font-inter",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Portfolio - Marcos Morua",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${noto.variable} antialiased  bg-bg text-textColor`}
      >
        <Sidebar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
